=== Manaswini0706/student-management-database/WEEK 6/students.dtd
<!ELEMENT students (student*)>
  <!ELEMENT student (name,rollno,marks)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT rollno (#PCDATA)>
  <!ELEMENT marks (#PCDATA)>
  <!ENTITY mark "0">
  <!ATTLIST student id CDATA #IMPLIED>

=== Manaswini0706/student-management-database/WEEK 6/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
  <student>
    <name>hello world</name>
    <rollno>20b81a0573</rollno>
    <marks>100</marks>
  </student>
  <student id="456">
    <name>hello world1</name>
    <rollno>20b81a0591</rollno>
    <marks>50</marks>
  </student>
  <student id="789">
    <name>hello world2</name>
    <rollno>20b81a0599</rollno>
    <marks>0</marks>
  </student>
</students>
